name: mupen64plus # you probably want to 'snapcraft register <name>'
title: "Mupen64Plus"
icon: data/Mupen64plus.svg
base: core18 # the base snap is the execution environment for this snap
version: '2.5.9' # just for humans, typically '1.2+git' or '1.3.2'
summary: Mupen64Plus is based off of mupen64, originally created by Hacktarux # 79 char long summary
description: |
  Mupen64Plus is a Nintendo 64 emulator based off of mupen64, originally 
  created by Hacktarux. This snap version includes Mupen64Core and all
  official plugins.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: [amd64, arm64]
    run-on: [amd64, arm64]

apps:
  m64py:
    desktop: mupen64plus.desktop
    command: bin/m64py
    plugs:
      - x11
      - wayland
      - opengl
      - pulseaudio
      - joystick
      - home
      - desktop
      - desktop-legacy
      - unity7

parts:
  mupen64plus-core:
    plugin: make
    #source: https://github.com/mupen64plus/mupen64plus-core.git
    source: https://github.com/iAmSomeone2/mupen64plus-core.git
    source-type: git
    source-tag: '2.5.9'
    source-depth: 1
    build-packages:
      - nasm
      - libsdl2-dev
      - libsdl-ttf2.0-dev
      - libpng-dev
      - libfreetype6-dev
      - zlib1g-dev
      - libgtk2.0-dev
      - libsamplerate0-dev
      - libqt4-dev
      - libopencv-dev
      - libopencv-core-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl-ttf2.0-0
      - libpng16-16
      - libfreetype6
      - zlib1g
      - libgtk2.0-0
      - libsamplerate0
      # Snap-specific deps are below here.
      - libslang2
      - libgl1
      - libglu1-mesa
      - libglx-mesa0
      - libglx0
      - libgles2
      - libopencv-core3.2
      - libusb-1.0-0
      - libarmadillo8
      - libgdal20
      - libogdi3.2
      - libcharls1
      - libaec0
      - libarpack2
      - libasn1-8-heimdal
      - libavcodec57
      - libavformat57
      - libavutil55
      - libblas3
      - libbluray2
      - libchromaprint1
      - libcrystalhd3
      - libcurl3-gnutls
      - libdap25
      - libdapclient6v5
      - libdc1394-22
      - libepsilon1
      - libexif12
      - libfreexl1
      - libfyba0
      - libgdcm2.8
      - libgeos-3.6.2
      - libgeos-c1v5
      - libgeotiff2
      - libgfortran-8-dev
      - libgif7
      - libgme0
      - libgomp1
      - libgphoto2-6
      - libgphoto2-port12
      - libgsm1
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkmlbase1
      - libkmldom1
      - libkmlengine1
      - libkrb5-26-heimdal
      - liblapack3
      - liblcms2-2
      - libldap-2.4-2
      - libldap-common
      - libilmbase12
      - libopencv-imgcodecs3.2
      - libopencv-imgproc3.2
      - libopencv-videoio3.2
      - libswscale4
    override-build: |
      cd projects/unix
      export OPENCV=1
      #export PREFIX="/root/parts/mupen64plus-core/install/usr/local"
      make all -j$(nproc)
      make install
  mupen64plus-video-glide64:
    after:
      - mupen64plus-core
    plugin: make
    source: https://github.com/mupen64plus/mupen64plus-video-glide64.git
    source-type: git
    source-tag: '2.5.9'
    source-depth: 1
    override-build: |
      cd projects/unix
      #export PREFIX="/root/parts/mupen64plus-video-glide64/install/usr/local"
      make all -j$(nproc)
      make install
  mupen64plus-video-glide64mk2:
    after:
        - mupen64plus-core
        - mupen64plus-video-glide64
    plugin: make
    source: https://github.com/mupen64plus/mupen64plus-video-glide64mk2.git
    source-type: git
    source-tag: '2.5.9'
    source-depth: 1
    build-packages: 
      - libboost-dev
      - libboost-all-dev
    stage-packages: 
      - libboost-filesystem1.65.1
    override-build: |
      cd projects/unix
      #export PREFIX="/root/parts/mupen64plus-video-glide64mk2/install/usr/local"
      make all -j$(nproc)
      make install
  mupen64plus-video-rice:
    after:
      - mupen64plus-core
    plugin: make
    source: https://github.com/mupen64plus/mupen64plus-video-rice.git
    source-type: git
    source-tag: '2.5.9'
    source-depth: 1
    override-build: |
      cd projects/unix
      #export PREFIX="/root/parts/mupen64plus-video-rice/install/usr/local"
      make all -j$(nproc)
      make install
  mupen64plus-video-z64:
    after:
      - mupen64plus-core
    plugin: make
    source: https://github.com/mupen64plus/mupen64plus-video-z64.git
    source-type: git
    source-tag: '2.5.9'
    source-depth: 1
    build-packages: 
      - libglew-dev
    stage-packages:
      - libglew2.0
    override-build: |
      cd projects/unix
      #export PREFIX="/root/parts/mupen64plus-video-z64/install/usr/local"
      make all -j$(nproc)
      make install
  mupen64plus-ui-console:
    after:
      - mupen64plus-core
    plugin: make
    source: https://github.com/mupen64plus/mupen64plus-ui-console.git
    source-type: git
    source-tag: '2.5.9'
    source-depth: 1
    override-build: |
      cd projects/unix
      #export PREFIX="/root/parts/mupen64plus-ui-console/install/usr/local"
      make all -j$(nproc)
      make install
  mupen64plus-rsp-z64:
    after:
      - mupen64plus-core
    plugin: make
    source: https://github.com/mupen64plus/mupen64plus-rsp-z64.git
    source-type: git
    source-tag: '2.5.9'
    source-depth: 1
    override-build: |
      cd projects/unix
      #export PREFIX="/root/parts/mupen64plus-rsp-z64/install/usr/local"
      make all -j$(nproc)
      make install
  mupen64plus-rsp-hle:
    after:
      - mupen64plus-core
    plugin: make
    source: https://github.com/mupen64plus/mupen64plus-rsp-hle.git
    source-type: git
    source-tag: '2.5.9'
    source-depth: 1
    override-build: |
      cd projects/unix
      #export PREFIX="/root/parts/mupen64plus-rsp-hle/install/usr/local"
      make all -j$(nproc)
      make install
  mupen64plus-rsp-cxd4:
    after:
        - mupen64plus-core
    plugin: make
    source: https://github.com/mupen64plus/mupen64plus-rsp-cxd4.git
    source-type: git
    source-tag: '2.5.9'
    source-depth: 1
    override-build: |
      cd projects/unix
      #export PREFIX="/root/parts/mupen64plus-rsp-cxd4/install/usr/local"
      make all -j$(nproc)
      make install
  mupen64plus-audio-sdl:
    after:
      - mupen64plus-core
    plugin: make
    source: https://github.com/mupen64plus/mupen64plus-audio-sdl.git
    source-type: git
    source-tag: '2.5.9'
    source-depth: 1
    build-packages: 
      - libspeexdsp-dev
    stage-packages: 
      - libspeexdsp1
    override-build: |
      cd projects/unix
      #export PREFIX="/root/parts/mupen64plus-audio-sdl/install/usr/local"
      make all -j$(nproc)
      make install
  mupen64plus-input-sdl:
    after:
      - mupen64plus-core
    plugin: make
    source: https://github.com/mupen64plus/mupen64plus-input-sdl.git
    source-type: git
    source-tag: '2.5.9'
    source-depth: 1
    override-build: |
      cd projects/unix
      #export PREFIX="/root/parts/mupen64plus-input-sdl/install/usr/local"
      make all -j$(nproc)
      make install
  mupen64plus-video-arachnoid:
    after:
      - mupen64plus-core
    plugin: make
    source: https://github.com/mupen64plus/mupen64plus-video-arachnoid.git
    source-type: git
    source-tag: '2.5.9'
    source-depth: 1
    override-build: |
      cd projects/unix
      #export PREFIX="/root/parts/mupen64plus-video-arachnoid/install/usr/local"
      make all -j$(nproc)
      make install

  pysdl2:
    after:
      - mupen64plus-core
    plugin: python
    python-version: python3
    source: https://bitbucket.org/marcusva/py-sdl2/downloads/PySDL2-0.9.5.tar.gz
    source-type: tar
    source-checksum: sha256/500eeef667a12ab2790b9fbf25f24b2e1de3bdc9d0b07fd94112ad486149e276

  mupen64plus-ui-python:
    after:
      - mupen64plus-core
      - pysdl2
    plugin: python
    python-version: python3
    source: https://github.com/mupen64plus/mupen64plus-ui-python.git
    source-type: git
    # source-tag: '0.2.4'
    source-depth: 1
    requirements:
      - requirements.txt # The latest dev versions use a requirements.txt file (2019-05-06)
    python-packages:
      - PyQt5
    build-packages:
      - python-pyqt5
      - pyqt5-dev-tools
      - python-pyqt5.qtopengl
      - libsdl2-dev
    stage-packages: 
      - libegl1
      - libqt5core5a
      - libqt5opengl5
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libepoxy0
      - libevdev2
      - libgtk-3-0
      - libgudev-1.0-0
      - libinput10
      - libmtdev1
      - libpulse-mainloop-glib0
      - libwacom2
      - libwayland-server0
      - libxkbcommon-x11-0
      - libxcb-xkb1
      - python3-pyqt5